import jsPDF from 'jspdf';

interface ProductBrochureData {
  name: string;
  description: string;
  price: number;
  specifications: Record<string, any>;
  images: string[];
}

export const generateProductBrochure = (product: ProductBrochureData) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(24);
  doc.setTextColor(37, 99, 235); // Primary blue
  doc.text('LuxeShowcase', 20, 30);
  
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.text('Product Brochure', 20, 45);
  
  // Product Name
  doc.setFontSize(20);
  doc.setTextColor(37, 99, 235);
  doc.text(product.name, 20, 70);
  
  // Price
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(`Price: $${product.price}`, 20, 85);
  
  // Description
  doc.setFontSize(12);
  doc.text('Description:', 20, 105);
  
  // Split description into lines
  const descriptionLines = doc.splitTextToSize(product.description, 170);
  doc.text(descriptionLines, 20, 115);
  
  let yPosition = 115 + (descriptionLines.length * 5) + 20;
  
  // Specifications
  if (Object.keys(product.specifications).length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235);
    doc.text('Specifications:', 20, yPosition);
    yPosition += 10;
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    
    Object.entries(product.specifications).forEach(([key, value]) => {
      doc.text(`• ${key}: ${value}`, 25, yPosition);
      yPosition += 6;
    });
    
    yPosition += 10;
  }
  
  // Features
  doc.setFontSize(14);
  doc.setTextColor(37, 99, 235);
  doc.text('Why Choose This Product:', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  
  const features = [
    'Premium quality materials and construction',
    'Backed by our satisfaction guarantee',
    'Expert customer support available',
    'Fast and secure shipping',
    'Competitive pricing with value guarantee'
  ];
  
  features.forEach(feature => {
    doc.text(`• ${feature}`, 25, yPosition);
    yPosition += 6;
  });
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by LuxeShowcase - Premium Product Showcase', 20, 280);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 285);
  
  // Contact Information
  doc.text('Contact us: hello@luxeshowcase.com | +1 (555) 123-4567', 20, 290);
  
  // Save the PDF
  doc.save(`${product.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_brochure.pdf`);
};